-- Generated from Alembic revision 20260410_000001.
-- Alembic is the schema source of truth; keep this file as a mirror.
create table if not exists public.studios (
    id integer generated by default as identity primary key,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name varchar(200) not null,
    cover_image varchar(500),
    description text,
    city varchar(100),
    district varchar(100),
    address varchar(500),
    longitude double precision,
    latitude double precision,
    equipment jsonb,
    room_count integer default 1,
    room_features jsonb,
    price_per_hour integer,
    price_per_day integer,
    price_note varchar(500),
    booking_url varchar(500),
    booking_note varchar(200),
    contact_name varchar(100),
    contact_phone varchar(50),
    contact_wechat varchar(100),
    portfolio_images jsonb,
    portfolio_links jsonb,
    tags jsonb,
    is_active boolean default true
);

create index if not exists ix_studios_id on public.studios (id);
create index if not exists ix_studios_city on public.studios (city);
create index if not exists ix_studios_is_active on public.studios (is_active);

create table if not exists public.editors (
    id integer generated by default as identity primary key,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name varchar(200) not null,
    avatar varchar(500),
    bio text,
    skills jsonb,
    software jsonb,
    experience_years integer default 0,
    specialties jsonb,
    price_per_episode integer,
    price_per_hour integer,
    price_note varchar(500),
    contact_phone varchar(50),
    contact_wechat varchar(100),
    contact_email varchar(200),
    portfolio_url varchar(500),
    portfolio_images jsonb,
    portfolio_links jsonb,
    tags jsonb,
    rating integer default 0,
    is_active boolean default true
);

create index if not exists ix_editors_id on public.editors (id);
create index if not exists ix_editors_is_active on public.editors (is_active);

create table if not exists public.business_contacts (
    id integer generated by default as identity primary key,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name varchar(200) not null,
    avatar varchar(500),
    company varchar(200),
    title varchar(200),
    bio text,
    business_type varchar(100),
    industry varchar(100),
    budget_range varchar(100),
    cooperation_types jsonb,
    contact_phone varchar(50),
    contact_wechat varchar(100),
    contact_email varchar(200),
    case_images jsonb,
    case_links jsonb,
    reference_podcasts jsonb,
    tags jsonb,
    rating integer default 0,
    is_active boolean default true
);

create index if not exists ix_business_contacts_id on public.business_contacts (id);
create index if not exists ix_business_contacts_is_active on public.business_contacts (is_active);
