import type { Studio, StudioListItem } from './types'

export const studioSnapshot: Studio[] = [
  {
    id: 7,
    name: '788创意社区录音室（房间在调整，还没确定最终信息）',
    cover_image: null,
    description: '开放时间: 周一至周五7:00-22:00 ；周六至周日9:00-22:00',
    open_hours: null,
    city: '上海',
    district: '普陀区',
    address: '上海市普陀区金沙江路788号和胤广场 5F',
    longitude: 121.393,
    latitude: 31.242,
    equipment: ['罗德Caster Pro II二代播客调音台、2支罗德 podmic话筒。'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: 80,
    price_per_day: null,
    price_note: '收费',
    charging_method: '按小时收费',
    booking_url: null,
    booking_note: '收费，雅邑合集小程序预约，工作日7:00-18:00 80r/h；18：00-22:00 120/h；周末9:00-18:00 80/h；周末18:00-22:00 120/h。',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客录音室'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997553',
    updated_at: '2026-04-09 19:32:03.799112',
  },
  {
    id: 4,
    name: 'CCPA S36 中文播客艺术中心',
    cover_image: null,
    description: '开放时间: 周一至周五10:00-18:00',
    open_hours: null,
    city: '上海',
    district: '静安区',
    address: '上海市静安区天目西路99号丽丰天际中心 F36',
    longitude: 121.452,
    latitude: 31.246,
    equipment: ['4支罗德podmic话筒', '罗德Caster Pro二代调音台。'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: null,
    price_per_day: null,
    price_note: '收费',
    charging_method: '按时段收费',
    booking_url: null,
    booking_note: '收费，99r/2h，仅对CPA社员开放使用，CPA公众号预约',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客空间'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997551',
    updated_at: '2026-04-09 19:32:03.799110',
  },
  {
    id: 6,
    name: 'Inspirer播客间',
    cover_image: null,
    description: '开放时间: 周一到周五，10:00-21:00；周六周日，18：00-21:00',
    open_hours: null,
    city: '上海',
    district: '',
    address: '上海·长宁区凯旋路1205号2号楼2楼N室Inspirer灵感来了俱乐部',
    longitude: 121.422,
    latitude: 31.212,
    equipment: ['4支Maono闪克 pd300x 麦克风设备'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: 60,
    price_per_day: null,
    price_note: '收费',
    charging_method: '按小时收费',
    booking_url: null,
    booking_note: '收费，60r/h，微信预约（13061985080）',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客空间'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997553',
    updated_at: '2026-04-09 19:32:03.799111',
  },
  {
    id: 2,
    name: '内容中苔播客自助录音间',
    cover_image: null,
    description: '开放时间: 周一至周日 0:00-24:00',
    open_hours: null,
    city: '上海',
    district: '杨浦区',
    address: '上海市杨浦区淞沪路398号创智天地8号楼B1层05会议室',
    longitude: 121.514,
    latitude: 31.298,
    equipment: ['罗德 Caster Pro 一代播客调音台', '4支罗德 Podmic 麦克风', '配有视频播客灯光方案。'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: 50,
    price_per_day: null,
    price_note: '收费',
    charging_method: '按小时收费',
    booking_url: null,
    booking_note: '收费，50r/h，内容中苔播客空间小程序/内容中苔创作空间公众号预约',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客录音室'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997549',
    updated_at: '2026-04-09 19:32:03.799109',
  },
  {
    id: 5,
    name: '十二海里编辑部',
    cover_image: null,
    description: '开放时间: 周一至周日10:00-22:00',
    open_hours: null,
    city: '上海',
    district: '长宁区',
    address: '上海市长宁区愚园路753号嘉春753园区c栋101号',
    longitude: 121.433,
    latitude: 31.22,
    equipment: ['罗德 Caster Pro II调音台、4支Rode PODMiC麦克风、4套Rode NTH-100耳机。'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: null,
    price_per_day: null,
    price_note: '免费',
    charging_method: '免费',
    booking_url: null,
    booking_note: '免费，十二海里编辑部微信联系预约',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客空间'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997552',
    updated_at: '2026-04-09 19:32:03.799111',
  },
  {
    id: 1,
    name: '小宇宙录音室',
    cover_image: null,
    description: '开放时间: 周一至周五14:30-18:00',
    open_hours: null,
    city: '上海',
    district: '杨浦区',
    address: '上海市杨浦区淞沪路303号6层',
    longitude: 121.5144,
    latitude: 31.2993,
    equipment: ['罗德Caster Pro调音台', '4支罗德podmic话筒。'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: null,
    price_per_day: null,
    price_note: '免费',
    charging_method: '免费',
    booking_url: null,
    booking_note: '免费，小宇宙播客公众号预约',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客录音室'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997545',
    updated_at: '2026-04-09 19:32:03.799105',
  },
  {
    id: 3,
    name: '尽管吱声录音工作室',
    cover_image: null,
    description: '开放时间: 周一至周五9:00-21:00；周六至周日10:00-21:00',
    open_hours: null,
    city: '上海',
    district: '杨浦区',
    address: '上海市杨浦区宁国路399号碧桂园中心1号楼',
    longitude: 121.527,
    latitude: 31.287,
    equipment: ['2支罗德麦', '2支舒尔58麦'],
    room_count: 1,
    room_features: null,
    capacity: null,
    need_own_equipment_for_video: null,
    price_per_hour: null,
    price_per_day: null,
    price_note: '免费',
    charging_method: '免费',
    booking_url: null,
    booking_note: '免费，工作室微信或小红书私信预约',
    booking_qr_image: null,
    contact_name: null,
    contact_phone: null,
    contact_wechat: null,
    contact_info: null,
    portfolio_images: null,
    portfolio_links: null,
    tags: ['播客录音室'],
    is_active: true,
    created_at: '2026-04-09 18:25:28.997550',
    updated_at: '2026-04-09 19:32:03.799110',
  },
]

export const studioSnapshotList: StudioListItem[] = studioSnapshot.map(studio => ({
  id: studio.id,
  name: studio.name,
  cover_image: studio.cover_image,
  city: studio.city,
  district: studio.district,
  address: studio.address,
  longitude: studio.longitude,
  latitude: studio.latitude,
  capacity: studio.capacity,
  need_own_equipment_for_video: studio.need_own_equipment_for_video,
  contact_info: studio.contact_info,
  price_per_hour: studio.price_per_hour,
  price_per_day: studio.price_per_day,
  tags: studio.tags,
  charging_method: studio.charging_method,
  is_active: studio.is_active,
}))
